---
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Include OS-specific variables.
    include_vars: "{{ playbook_dir }}/defaults/main.yml"
  - import_tasks: "tasks/main.yml"
